sudo: required
services:
    - docker

before_install:
    - docker build -t tusharsingh62/docker-react -f Dockerfile.dev .

script: 
    - docker run tusharsingh62/docker-react npm run test -- --coverage
